/*
 * This source file was generated by the Gradle 'init' task
 */
package pa7;

public class Q1 {
    
    public void rotateImage(int[][] matrix) {    
        for(int i=0; i<=matrix.length-1; i++){
            for(int j = 0; j<= i-1; j++){
                int holder = matrix[i][j];
                matrix[i][j] = matrix[j][i];
                matrix[j][i] = holder;
            }
        }
        
        for(int i=0; i<= matrix.length-1; i++){
            for(int j=0;j<matrix[i].length-1-j; j++){
                int holder = matrix[i][j];
                matrix[i][j] = matrix[i][matrix[i].length-1-j];
                matrix[i][matrix[i].length-1-j] = holder;
            }
        }

    }
}
