/*
 * This source file was generated by the Gradle 'init' task
 */
package pa7;

public class Q2 {
    
    public int numberOfIslands(char[][] grid) {
        int count=0;
        for(int i=0;i<grid.length;i++){
            for(int j=0;j<grid[0].length;j++){
                if(grid[i][j]=='1'){
                    findIsland(grid,i,j);
                    count++;
                }
            }
        }
        return count;
    }

    public void findIsland(char[][] grid,int i,int j){
        if ((i < 0) || (i >=grid.length) || (j < 0) || (j >= grid[0].length) || (grid[i][j] != '1')) {
            return;
        }
        grid[i][j] = 'V';
        findIsland(grid,i,j-1); // left
        findIsland(grid,i,j+1); // right
        findIsland(grid,i-1,j); // up
        findIsland(grid,i,j+1); // right
        findIsland(grid,i+1,j); // down
    }

}
