/*
 * This source file was generated by the Gradle 'init' task
 */
package pa7;

public class Q3{
    
    public static int maxAreaOfIsland(int[][] grid) {
        int maxsize = 0;
        for(int i=0;i<grid.length;i++){
            for(int j=0;j<grid[i].length;j++){
                if(grid[i][j]== 1){
                    int currsize = findIsland(grid,i,j);
                    if (currsize > maxsize)
                        maxsize = currsize;
                }
            }
        }
        return maxsize;
    }

    private static int findIsland(int[][] grid,int i,int j){
        if ((i < 0) || (i >= grid.length) || (j < 0) || (j >= grid[i].length) || (grid[i][j] != 1)) {
            return 0;
        }
        grid[i][j] = 5; //visited

        int area = 1;

        area += findIsland(grid,i,j-1); 
        area += findIsland(grid,i,j+1); 
        area += findIsland(grid,i-1,j); 
        area += findIsland(grid,i+1,j); 

        return area;
    }
}
